version: 2
job_common: &job_common
  docker:
    - image: circleci/node:8.11.3
  working_directory: ~/Voting
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      sudo npm install -g truffle
      npm install

jobs:
  # build:
  #   <<: *job_common
  #   steps:
  #     - checkout
  #     - <<: *step_restore_cache
  #     - <<: *step_setup_global_packages
  #     - run:
  #         name: "Build code for Electus Protocol"
  #         command: truffle compile
  #     - <<: *step_save_cache
  unit-test:
    <<: *job_common
    steps:
      - checkout
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Run Tests for Voting"
          command: npm run test
      - <<: *step_save_cache
      # Save test results
      - store_test_results:
          path: /tmp/test-results
  test-coverage:
    <<: *job_common
    steps:
      - checkout
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - setup_remote_docker
      - run:
          name: "Running unit tests with coverage"
          command: npm run coverage
      - run:
          name: "Upload Coverage"
          command: bash <(curl -s https://codecov.io/bash)
      # Save coverage artifacts
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  commit:
    jobs:
      - unit-test
      - test-coverage
